# Generated by Django 5.0.4 on 2024-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hindi', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Total_Score_10th', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Maths2', models.IntegerField()),
                ('Total_Score_12th', models.IntegerField()),
            ],
        ),
    ]
