# Generated by Django 5.0.4 on 2024-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
