# Generated by Django 5.1.4 on 2024-12-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_yourmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YourModel",
        ),
    ]
