# Generated by Django 5.0.4 on 2024-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='English',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_records',
        ),
    ]
