# Generated by Django 5.0.4 on 2024-04-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_english_student_dob_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='English',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Hindi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Maths2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Science',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Total_Score_10th',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Total_Score_12th',
            field=models.IntegerField(default=0),
        ),
    ]
