# Generated by Django 5.0.4 on 2024-04-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_chemistry_alter_student_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Overall_Score',
            field=models.IntegerField(default=0),
        ),
    ]
