# Generated by Django 5.0.6 on 2024-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_attendance_fee_personaldetails_semester_subjectgrade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="hostel_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fee",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fee",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fee",
            name="transport_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fee",
            name="tuition_fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
