# Generated by Django 5.0.6 on 2024-07-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_fee_hostel_fee_alter_fee_paid_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="hostel_fee",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="fee",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="fee",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="fee",
            name="transport_fee",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="fee",
            name="tuition_fee",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
